### PR TITLE
delete defs

### PR DESCRIPTION
**Pull request by hansvancalster**
## Task list

Steps by contributor:

-   [ ] Add description to this pull request (under "## Description")
-   [ ] Open the dropdown (triangle) near 'create pull request' and choose 'Create draft pull request'
-   [ ] Check for potential problems by running `protocolhelper::check_frontmatter()` and address them
-   [ ] Check for potential problems by running `protocolhelper::check_structure()` and address them
-   [ ] Add further commits if needed and push them to GitHub
-   [ ] Update the protocol-specific `NEWS.Rmd`
-   [ ] Mark the pull request as 'ready for review'

Review steps for the author(s):

-   [ ] Add reviewers, at least one subject-matter specialist and one administrator
-   [ ] Wait for review comments and address them
-   [ ] Iterate until reviewer approvals (merging the pull request will be done by an administrator)
-   [ ] Verify that the checks done by continuous integration succeeded. These will check if `protocolhelper::check_frontmatter()` and `protocolhelper::check_structure()` succeeded without errors.

To be done by an administrator after review: see [guidelines for admins](https://github.com/inbo/protocolsource/blob/main/RELEASES.md).

### CODE REVIEW

**Comment by hansvancalster** [comment]
In this case the changes are flagged, but the error messages are not that clear. The issue is here that I make a change (revision) in `sfp-001-nl`, but I incorrectly specified `sfp-001-en` as branch name. However, I think we cannot really decide in an automatic way if the branch name is wrong or a change was made in the wrong folder (we can't read minds). Anyway, errors are triggered and that should trigger some critical thinking about what exactly is wrong. What do you think @ElsLommelen ?

**Comment by ElsLommelen** [comment]
The message clearly states you have to make another branch to push the changes to this protocol, so with some critical thinking you may guess that the branch name is wrong.  And you can have a look at the folder name to derive the correct name of the protocol/branch.  But indeed, users probably won't think about this possibility, so we somehow have to add it in the message.

A possibility would be to rephrase the message to make it more clear to the user, and add the name of the changed protocol in it as well, for instance: `Branch sfp-001-en contains changes to files which belong to protocol sfp-001-nl and not to protocol sfp-001-en, and these changes will not be passed to the website. Please remove these changes from this branch and start a new branch for changes to sfp-001-nl. Changes to be removed: source/sfp/0_generic/sfp_001_nl_vervanging_terrest/02_onderwerp.Rmd`.  But problems with this are:
- what if changes are made to multiple protocols?  And how easy/difficult is it to derive the protocol_code from the folder name (in this case it seems rather easy, but the script in the yaml is often a pain in the ass for seemingly easy things)?
- what if changes are made to files other than the protocols?
- to cover all these different cases (changes in 1 or multiple protocols, changes in other files), makes the code more complicated.

Maybe we could think about a simple addition to the error message that gives users an additional hint about this situation, such as `Maybe a wrong protocol_code is used as branch name?`.  This is no big deal for us (and avoids having to read their mind), but it should be enough to trigger users to check their branch name with the protocol_code, I think.  This is just a first suggestion, feel free to propose a better message. ;-)

**Comment by hansvancalster** [comment]
I would indeed prefer the simplest solution and that is adding `Maybe a wrong protocol_code is used as branch name?` to `docker/entrypoint_check.sh`. Can you make this change?

**Comment by ElsLommelen** [comment]
Where do I add it?  In the end, or before `Changes to be removed:`, or before `Please remove these changes ...`?
Do you want me to build a new docker with this addition, or do I just change the code in protocolsource so the change will be added on a next build (e.g. after a more crucial change, or after merging all changes to the main of protocolsource)?

**Comment by hansvancalster** [comment]
Before `Changes to be ...`. No need to rebuild the docker - there are other changes coming - just change the code in protocolsource.

**Pull request closed without merging**
